//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""KeyBoardMap"",
            ""id"": ""8e9d2394-16a0-4716-8c19-f9ca8d1746c4"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""21695179-368b-4240-8f07-75d5f59dc2c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""55538f75-6e48-4fb4-a59f-e432c305fbe9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyBoardScheme"",
            ""bindingGroup"": ""KeyBoardScheme"",
            ""devices"": []
        }
    ]
}");
        // KeyBoardMap
        m_KeyBoardMap = asset.FindActionMap("KeyBoardMap", throwIfNotFound: true);
        m_KeyBoardMap_Jump = m_KeyBoardMap.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyBoardMap
    private readonly InputActionMap m_KeyBoardMap;
    private IKeyBoardMapActions m_KeyBoardMapActionsCallbackInterface;
    private readonly InputAction m_KeyBoardMap_Jump;
    public struct KeyBoardMapActions
    {
        private @PlayerInputActions m_Wrapper;
        public KeyBoardMapActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_KeyBoardMap_Jump;
        public InputActionMap Get() { return m_Wrapper.m_KeyBoardMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyBoardMapActions set) { return set.Get(); }
        public void SetCallbacks(IKeyBoardMapActions instance)
        {
            if (m_Wrapper.m_KeyBoardMapActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_KeyBoardMapActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_KeyBoardMapActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_KeyBoardMapActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_KeyBoardMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public KeyBoardMapActions @KeyBoardMap => new KeyBoardMapActions(this);
    private int m_KeyBoardSchemeSchemeIndex = -1;
    public InputControlScheme KeyBoardSchemeScheme
    {
        get
        {
            if (m_KeyBoardSchemeSchemeIndex == -1) m_KeyBoardSchemeSchemeIndex = asset.FindControlSchemeIndex("KeyBoardScheme");
            return asset.controlSchemes[m_KeyBoardSchemeSchemeIndex];
        }
    }
    public interface IKeyBoardMapActions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
